const VA_LIST = [
  {
    id: "va-001",
    name: "Maria Santos",
    role: "Customer Service Specialist",
    avatar: "MS",
    rating: 4.9,
    reviews: 124,
    experience: "5 yrs",
    skills: ["Live Chat", "Email Support", "CRM", "Zendesk", "HubSpot"],
    availability: "Available",
    hourlyRate: 12,
    completedJobs: 87,
    responseTime: "< 1 hr",
    bio: "Dedicated CSR with 5 years in SaaS and eCommerce support. Expert in de-escalation and CRM documentation.",
    categoryIds: ["csr"],
    location: "Cebu, PH",
    languages: "English, Filipino"
  },
  {
    id: "va-002",
    name: "James Reyes",
    role: "Technical Support Engineer",
    avatar: "JR",
    rating: 4.8,
    reviews: 98,
    experience: "6 yrs",
    skills: ["Tier 1\u20132 Support", "API Troubleshooting", "Shopify", "SaaS Backends"],
    availability: "Available",
    hourlyRate: 15,
    completedJobs: 63,
    responseTime: "< 2 hrs",
    bio: "Technical support pro with deep eCommerce and SaaS platform knowledge. Handles complex escalations with ease.",
    categoryIds: ["csr", "tech"],
    location: "Manila, PH",
    languages: "English, Filipino"
  },
  {
    id: "va-003",
    name: "Angela Cruz",
    role: "Web Developer",
    avatar: "AC",
    rating: 5,
    reviews: 57,
    experience: "4 yrs",
    skills: ["WordPress", "Webflow", "Shopify", "Landing Pages", "SEO Basics"],
    availability: "Available",
    hourlyRate: 18,
    completedJobs: 45,
    responseTime: "< 3 hrs",
    bio: "Full-stack web developer specializing in conversion-optimized builds on WordPress and Webflow.",
    categoryIds: ["tech", "digital"],
    location: "Davao, PH",
    languages: "English, Filipino"
  },
  {
    id: "va-004",
    name: "Carlo Mendoza",
    role: "Social Media Manager",
    avatar: "CM",
    rating: 4.7,
    reviews: 83,
    experience: "3 yrs",
    skills: ["Content Strategy", "Copywriting", "Canva", "Meta Ads", "Scheduling"],
    availability: "Busy",
    hourlyRate: 11,
    completedJobs: 72,
    responseTime: "< 4 hrs",
    bio: "Creative SMM who builds engaging content calendars and drives organic reach for lifestyle and service brands.",
    categoryIds: ["creative"],
    location: "Cebu, PH",
    languages: "English, Filipino"
  },
  {
    id: "va-005",
    name: "Sofia Lim",
    role: "Video & Graphic Designer",
    avatar: "SL",
    rating: 4.9,
    reviews: 66,
    experience: "5 yrs",
    skills: ["Premiere Pro", "After Effects", "Canva", "Brand Assets", "Reels"],
    availability: "Available",
    hourlyRate: 14,
    completedJobs: 51,
    responseTime: "< 2 hrs",
    bio: "Visual storyteller producing short-form video and brand creatives for social-first campaigns.",
    categoryIds: ["creative"],
    location: "Manila, PH",
    languages: "English, Filipino"
  },
  {
    id: "va-006",
    name: "Ryan Dela Cruz",
    role: "CRM & Automation Specialist",
    avatar: "RD",
    rating: 4.8,
    reviews: 44,
    experience: "4 yrs",
    skills: ["GoHighLevel", "HubSpot", "Zapier", "Email Automation", "Funnels"],
    availability: "Available",
    hourlyRate: 16,
    completedJobs: 38,
    responseTime: "< 2 hrs",
    bio: "Systems builder focused on CRM setups, automation workflows, and funnel builds that convert.",
    categoryIds: ["digital"],
    location: "Iloilo, PH",
    languages: "English, Filipino"
  },
  {
    id: "va-007",
    name: "Patricia Gomez",
    role: "SaaS Platform Manager",
    avatar: "PG",
    rating: 4.6,
    reviews: 29,
    experience: "3 yrs",
    skills: ["White-Label Setup", "Platform Onboarding", "Client Management", "SaaS Tools"],
    availability: "On Leave",
    hourlyRate: 13,
    completedJobs: 22,
    responseTime: "< 6 hrs",
    bio: "SaaS specialist experienced in white-label platform configuration and client onboarding workflows.",
    categoryIds: ["saas"],
    location: "Cebu, PH",
    languages: "English, Filipino"
  },
  {
    id: "va-008",
    name: "Mark Villanueva",
    role: "AI & Automation Builder",
    avatar: "MV",
    rating: 4.9,
    reviews: 38,
    experience: "3 yrs",
    skills: ["AI Chatbots", "Make.com", "Zapier", "API Integrations", "n8n"],
    availability: "Available",
    hourlyRate: 20,
    completedJobs: 31,
    responseTime: "< 1 hr",
    bio: "AI-first automation architect building intelligent workflows, chatbots, and CRM integrations at scale.",
    categoryIds: ["digital"],
    location: "Manila, PH",
    languages: "English, Filipino"
  }
];
const AVAILABILITY_COLORS = {
  "Available": { bg: "#f0fdf4", color: "#16a34a", dot: "#22c55e" },
  "Busy": { bg: "#fffbeb", color: "#d97706", dot: "#f59e0b" },
  "On Leave": { bg: "#fef2f2", color: "#dc2626", dot: "#ef4444" }
};
const SORT_OPTIONS = ["Top Rated", "Most Reviews", "Lowest Rate", "Most Experienced"];
export {
  AVAILABILITY_COLORS,
  SORT_OPTIONS,
  VA_LIST
};
